import type { Metadata } from "next";
import { Atkinson_Hyperlegible_Mono, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientShell from "./ClientShell";

const Atkinson = Atkinson_Hyperlegible_Mono({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${Atkinson.variable} ${geistMono.variable} antialiased`}>
        <ClientShell>{children}</ClientShell>
      </body>
    </html>
  );
}
